### ISSUE TITLE
Layouting

### ISSUE THREAD

**Issue by arjunmenon** [ColleagueRiley/RSGL#6]
Hey, maybe considering adding support for [Yoga](https://github.com/facebook/yoga) for containers? This can be very flexible to use with all widgets?
_Not sure if there is a separate discussion forum or irc, so posting here._

Also as a suggestion, for widgets to look modern, styling can be delegated to a perhaps a css-style parser?

**Comment by ColleagueRiley** [comment]
Hello, there is no other area for separate discussion due to the lack of community. I do have a discord server reserved for RSGL that I may reopen if it becomes necessary. Feel free to DM me on discord if you prefer that format.

Although I do not like the idea of a web-based front end for software development, I do understand the interest in it. One of my goal in RSGL's design is to ensure the user's design choices are not limited. So I would be happy to find a way to allow RSGL to work with other software such as Yoga. 

As for a "more modern" design, this seems vague. I'm not really the artistic type and would like to know what you want more specifically.
