### ISSUE TITLE
Use with PortableGL?

### ISSUE THREAD

**Issue by tomas** [ColleagueRiley/RSGL#7]
Hi, just found out about your project. Looks nice!

I noticed that RGFW has an OPENGL_SOFTWARE option in the code, but it assumes you want to use OSMesa (in Linux at least). I was wondering if it would be possible to use the lighter [PortableGL](https://github.com/rswinkle/PortableGL) instead. It's not a 1:1 replacement but it seems like a good fit, considering the spirit of both projects of being lightweight alternatives.

What do you think?

**Comment by ColleagueRiley** [comment]
RGFW includes support for OSMesa via `#define RGFW_OSMESA`. `OPENGL_SOFTWARE` is not the same thing, it just asks for the OpenGL software rendering drivers to be used. (eg [softpipe](https://docs.mesa3d.org/systems.html) 

For example, for linux it sets `LIBGL_ALWAYS_SOFTWARE=1`. 

I've seen PortableGL around a few times, I believe it can be used with RGFW without any changes. 

If you'd like, I can make a PortableGL example for RGFW or you could ask PortableGL to make a RGFW example.

**Comment by tomas** [comment]
> I can make a PortableGL example for RGFW

This would be great!

**Comment by ColleagueRiley** [comment]
@tomas I've added a [PortableGL example](https://github.com/ColleagueRiley/RGFW/blob/main/examples/portableGL/main.c).

**Comment by tomas** [comment]
Wow, that was fast! Thank you

**Comment by tomas** [comment]
I was looking at your RSGL project. Is there anything additional needed in order to make the "PortableGL mode" work for [those examples](https://github.com/ColleagueRiley/RSGL/tree/main/examples)?

**Comment by ColleagueRiley** [comment]
> I was looking at your RSGL project. Is there anything additional needed in order to make the "PortableGL mode" work for [those examples](https://github.com/ColleagueRiley/RSGL/tree/main/examples)?

Buffer rendering works with RSGL as seen in [RSGL-DOOM](https://github.com/ColleagueRiley/RSGL-DOOM)

However, there will still probably be some problems caused by `RGL`. For example, it loads the modern OpenGL functions it needs. You can tell it not to load those functions using `#define RGL_NO_GL_LOADER`.

Besides that, I don't know if it'll work by default. 

I have RSGL open right now so I can test that in a minute

**Comment by tomas** [comment]
Ok thanks! If you could provide a quick example it would be great. :)

**Comment by ColleagueRiley** [comment]
Update: 

I don't think RGL is compatible with portableGL because RGL uses functions such as `glBindAttribLocation`. 

As far as I'm aware I don't think there's a way to make RGL's modern OpenGL layer directly compatible with portableGL and I would have to write a portableGL layer instead. 

This also means that RSGL's draw functions are not directly compatible with portableGL. Although there is an RSGL function, `RSGL_getDrawInfo`, that could be used to render RSGL's draw data using portableGL without directly messing with RGL.

**Comment by tomas** [comment]
Oh I see. How would one use `RSGL_getDrawInfo` in order to skip using RGL for drawing stuff?

**Comment by ColleagueRiley** [comment]
@tomas 
First, you'd add `#define RGL_NO_RENDER` so that way RGL does not render.
Then you'd use the information from the `RGL_INFO struct` provided by `RSGL_getDrawInfo` to draw with.

Although, in the future, I may move every draw call to be in `RSGL_basicDraw` so that way instead of using `RSGL_getDrawInfo`, you'd define your own `RSGL_basicDraw`.

**Comment by tomas** [comment]
Gotcha, thanks

By the way I hit a snag trying to build RGFW with EGL, should I open a new issue?

**Comment by ColleagueRiley** [comment]
Sure, I've not tested the EGL code so I'm not surprised it has some issues.

**Comment by ColleagueRiley** [comment]
> Oh I see. How would one use `RSGL_getDrawInfo` in order to skip using RGL for drawing stuff?

I created an [example using OpenGL 1](https://github.com/ColleagueRiley/RSGL/blob/main/examples/custom_render_gl1.c), this can easily be edited to support PortableGL.

**Comment by ColleagueRiley** [comment]
@tomas Do you mind if I transfer this issue over to the RSGL repo?

**Comment by tomas** [comment]
Sure, go ahead!

**Comment by ColleagueRiley** [comment]
@tomas Here's an example I made for PortableGL and RSGL https://github.com/ColleagueRiley/RSGL-PortableGL

However, it is still WIP and does not properly render. But it should work as an example of how you would achieve this. 
I'll look into fixing the example when I'm less focused on my other projects.
